[project]
name = "product-categorizer"
version = "0.0.1"
requires-python = ">=3.11"

dependencies = [
  "fastapi",
  "uvicorn",
  "sqlalchemy",
  "psycopg[binary]",
  "pydantic",
  "pydantic-settings",
  "python-dotenv",
  "faiss-cpu",
  "python-multipart",
  "numpy",
  "pandas",
  "openpyxl",
  "google-genai",
  "google-cloud-aiplatform",
  "google-auth",
  "httpx",
  "pyyaml",
  "tqdm",
  "colorlog",
  "nltk",
  "pgvector",
  "llm-sdk-core",
  "llm-sdk-provider-gemini",
  "evan-logger",
  "jinja2"
]

[project.optional-dependencies]
embeddings = [
  "sentence-transformers",
  "torch"
]

[tool.pytest.ini_options]
pythonpath = ["src"]